# Generated by Django 3.0.5 on 2021-12-10 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_topping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='ate_added',
            new_name='date_added',
        ),
    ]
