# Generated by Django 3.0.5 on 2021-12-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_auto_20211210_0228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='NewComment',
        ),
    ]
